### ISSUE TITLE
'exclude_paths' or 'exclude_dirs'?

### ISSUE THREAD

**Issue by simonbcn** [Kha-kis/qbitunregistered#8]
I have changed my `config.json` to add `"exclude_files"` option and I have changed `"exclude_paths"` to `"exclude_dirs"` because I have seen in the `config.json.example` that it has changed:

```
...  
"//": "A list of paths to exclude from the orphaned file check.",
  "exclude_dirs": [
    "/multimedia2/juan/",
    "/multimedia2/pelis/",
    "/multimedia2/series/",
    "/multimedia2/backup-PC/",
    "/multimedia2/subidas/"
  ],

  "//": "Lista de ficheros a excluir",
  "exclude_files": [
    ".DS_Store"
  ],
...

```
 but nevertheless when I run it I get this error:

```
Traceback (most recent call last):
  File "/home/juan/fuentes/qbitunregistered/qbitunregistered.py", line 100, in <module>
    orphaned_files = check_files_on_disk(client, torrents, exclude_file_patterns=exclude_files, exclude_dirs=exclude_dirs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/juan/fuentes/qbitunregistered/scripts/orphaned.py", line 35, in check_files_on_disk
    if not any(excluded_path in file_path for excluded_path in exclude_paths) and not should_exclude_file(file):
                                                               ^^^^^^^^^^^^^
NameError: name 'exclude_paths' is not defined. Did you mean: 'exclude_dirs'?
```

**Comment by Kha-kis** [comment]
I believe this to be corrected with latest push.

**Comment by simonbcn** [comment]
Is it dead?

**Comment by Kha-kis** [comment]
This should now be fixed. Please confirm
